// src/lib/fa/strings.ts
/** All user-facing Persian copy. Components import keys — never hardcode UI strings. */
export const strings = {
  meta: {
    title: "دِ‌لِ‌پِ · منوی دیجیتال",
    description: "منوی دیجیتال کافه‌رستوران دِ‌لِ‌پِ",
  },
  brand: {
    /**
     * Locked brand string (D1). Never normalize or retype — includes ZWNJ.
     * Unicode: U+062F U+0650 U+200C U+0644 U+0650 U+200C U+067E U+0650
     */
    wordmark: "دِ‌لِ‌پِ",
  },
  public: {
    emptyTitle: "منو به‌زودی تکمیل می‌شود",
    emptyHint: "به‌زودی فهرست غذاها و نوشیدنی‌ها اینجا می‌آید.",
    footer: "دلِپ · منوی دیجیتال",
    homeLink: "بازگشت به منو",
    unavailable: "امروز تموم شد",
    fromPrice: "از",
    subtitle: "منوی دیجیتال",
    otherCategory: "سایر",
    categoriesAria: "دسته‌ها",
    percentSign: "٪",
    allSubcategories: "همه",
    subcategoriesAria: "زیردسته‌ها",
    expandVariants: "نمایش تنوع‌ها",
    collapseVariants: "بستن تنوع‌ها",
    loadingHint: "در حال آماده‌سازی سفره…",
    scrollHint: "منو",
    dockAria: "دسته‌های منو",
    tickerAria: "پیشنهادهای منو",
    peekAria: "جزئیات غذا",
    closePeek: "بستن",
  },
  hero: {
    pizza: "پیتزا",
    coffee: "قهوه",
    cookie: "کوکی",
    salad: "سالاد",
    coldDrink: "آیس‌کافه",
    dessert: "کیک",
    burger: "برگر",
    sandwich: "ساندویچ",
    solarAria: "مدار محصولات دِ‌لِ‌پِ",
  },
  badges: {
    POPULAR: "پرفروش",
    NEW: "جدید",
    SPICY: "تند",
    VEGETARIAN: "گیاهی",
  },
  errors: {
    notFoundTitle: "صفحه پیدا نشد",
    notFoundBody: "این صفحه وجود ندارد یا جابه‌جا شده است.",
    genericTitle: "مشکلی پیش آمد",
    genericBody: "لطفاً دوباره تلاش کنید.",
    retry: "تلاش دوباره",
    domain: {
      NOT_FOUND: "مورد نظر پیدا نشد",
      VALIDATION: "اطلاعات واردشده نامعتبر است",
      CATEGORY_NOT_EMPTY: "ابتدا محصولات این دسته را منتقل کنید",
      CATEGORY_HAS_PRODUCTS: "ابتدا محصولات این دسته را منتقل کنید",
      DEPTH_EXCEEDED: "عمق دسته‌بندی نمی‌تواند بیش از دو سطح باشد",
      DUPLICATE_NAME: "این نام از قبل استفاده شده است",
      INVALID_DISCOUNT: "قیمت با تخفیف باید کمتر از قیمت اصلی باشد",
      DISCOUNT_WITH_VARIANTS: "برای محصول دارای تنوع نمی‌توان تخفیف گذاشت",
      NOT_LEAF_CATEGORY: "محصول فقط در دستهٔ بدون زیرشاخه ثبت می‌شود",
      INVALID_REORDER: "ترتیب ارسال‌شده نامعتبر است",
      INVALID_UPLOAD: "فایل تصویر نامعتبر است",
      INVALID_CREDENTIALS: "نام کاربری یا رمز عبور نادرست است",
      UNAUTHORIZED: "نشست شما معتبر نیست",
      RATE_LIMITED: "تعداد تلاش‌ها بیش از حد مجاز است؛ ۱۵ دقیقه دیگر تلاش کنید",
    },
  },
  auth: {
    title: "ورود به پنل",
    username: "نام کاربری",
    password: "رمز عبور",
    submit: "ورود",
    logout: "خروج",
    changePassword: "تغییر رمز عبور",
    currentPassword: "رمز فعلی",
    nextPassword: "رمز جدید",
    savePassword: "ذخیره رمز",
    passwordChanged: "رمز عبور به‌روزرسانی شد",
  },
  admin: {
    productsHeading: "محصولات",
    categoriesHeading: "دسته‌بندی‌ها",
    settingsHeading: "تنظیمات",
    searchPlaceholder: "جستجوی محصول...",
    allCategories: "همه دسته‌ها",
    newProduct: "محصول جدید",
    editProduct: "ویرایش محصول",
    deleteProduct: "حذف محصول",
    deleteConfirmTitle: "حذف محصول",
    deleteConfirmDesc: "آیا از حذف {name} مطمئن هستید؟ این عمل قابل بازگشت نیست.",
    cancel: "انصراف",
    save: "ذخیره",
    delete: "حذف",
    name: "نام محصول",
    description: "توضیحات (مواد تشکیل‌دهنده)",
    price: "قیمت (تومان)",
    discount: "تخفیف",
    discountedPrice: "قیمت با تخفیف",
    discountActive: "فعال‌سازی تخفیف",
    available: "موجود",
    unavailable: "ناموجود",
    badges: "برچسب‌ها",
    variants: "تنوع‌ها (مثلاً سایز)",
    variantName: "نام تنوع",
    variantPrice: "قیمت",
    addVariant: "افزودن تنوع",
    image: "تصویر",
    uploadImage: "آپلود تصویر",
    replaceImage: "جایگزینی تصویر",
    removeImage: "حذف تصویر",
    cropImage: "برش تصویر",
    uploading: "در حال آپلود...",
    imageUploaded: "تصویر آپلود شد",
    imageUploadFailed: "آپلود تصویر ناموفق بود",
    imageTooLarge: "حجم تصویر باید کمتر از ۵ مگابایت باشد",
    imageTypeUnsupported: "فقط فایل‌های JPG، PNG و WebP مجاز هستند",
    productCreated: "محصول ایجاد شد",
    productUpdated: "محصول ویرایش شد",
    productDeleted: "محصول با موفقیت حذف شد",
    noResults: "هیچ محصولی یافت نشد.",
    reorderHint: "برای مرتب‌سازی، یک دسته انتخاب کنید",
    reorderAria: "جابه‌جایی برای مرتب‌سازی",
    unsavedChangesTitle: "تغییرات ذخیره‌نشده",
    unsavedChangesDesc: "تغییرات ذخیره‌نشده دارید. آیا مطمئن هستید که می‌خواهید این صفحه را ترک کنید؟",
    leave: "ترک صفحه",
    stay: "ماندن",
    preview: "پیش‌نمایش",
    backToSaved: "بازگشت به منوی ذخیره‌شده",
    settingsSaved: "تنظیمات ذخیره شد",
    restaurantName: "نام رستوران",
    unavailableMode: "وضعیت ناموجودها",
    unavailableMuted: "نمایش کم‌رنگ",
    unavailableHide: "پنهان کردن",
    systemMaintainedPrice: "قیمت بر اساس ارزان‌ترین تنوع محاسبه می‌شود",
    category: "دسته‌بندی",
    parentCategory: "دسته اصلی",
    childCategory: "زیردسته",
    selectPlaceholder: "انتخاب کنید",
    descriptionCounter: "نویسه",
    tickerTitle: "پیشنهادهای منو (نوار متحرک)",
    tickerHint:
      "ترتیب نمایش در نوار بالای منوی عمومی. اگر خالی باشد، به‌صورت خودکار از اولین محصولات موجود چیده می‌شود.",
    tickerAdd: "افزودن به پیشنهادها",
    tickerAddPlaceholder: "انتخاب محصول…",
    tickerEmpty: "هنوز محصولی انتخاب نشده؛ نوار به‌صورت خودکار پر می‌شود.",
    tickerSaved: "پیشنهادها ذخیره شد",
  },
} as const;
export type StringKey = typeof strings;