/** All user-facing Persian copy. Components import keys — never hardcode UI strings. */
export const strings = {
  meta: {
    title: "دِ‌لِ‌پِ · منوی دیجیتال",
    description: "منوی دیجیتال کافه‌رستوران دِ‌لِ‌پِ",
  },
  brand: {
    /**
     * Locked brand string (D1). Never normalize or retype — includes ZWNJ.
     * Unicode: U+062F U+0650 U+200C U+0644 U+0650 U+200C U+067E U+0650
     */
    wordmark: "دِ‌لِ‌پِ",
  },
  public: {
    emptyTitle: "منو به‌زودی تکمیل می‌شود",
    emptyHint: "به‌زودی فهرست غذاها و نوشیدنی‌ها اینجا می‌آید.",
    footer: "دلِپ · منوی دیجیتال",
    homeLink: "بازگشت به منو",
    unavailable: "امروز تموم شد",
    fromPrice: "از",
    subtitle: "منوی دیجیتال",
    otherCategory: "سایر",
    categoriesAria: "دسته‌ها",
    percentSign: "٪",
    allSubcategories: "همه",
    subcategoriesAria: "زیردسته‌ها",
    expandVariants: "نمایش تنوع‌ها",
    collapseVariants: "بستن تنوع‌ها",
    loadingHint: "در حال آماده‌سازی سفره…",
    scrollHint: "منو",
    dockAria: "دسته‌های منو",
    tickerAria: "پیشنهادهای منو",
    peekAria: "جزئیات غذا",
    closePeek: "بستن",
  },
  hero: {
    pizza: "پیتزا",
    coffee: "قهوه",
    cookie: "کوکی",
    salad: "سالاد",
    coldDrink: "آیس‌کافه",
    dessert: "کیک",
    burger: "برگر",
    sandwich: "ساندویچ",
    solarAria: "مدار محصولات دِ‌لِ‌پِ",
  },
  badges: {
    POPULAR: "پرفروش",
    NEW: "جدید",
    SPICY: "تند",
    VEGETARIAN: "گیاهی",
  },
  errors: {
    notFoundTitle: "صفحه پیدا نشد",
    notFoundBody: "این صفحه وجود ندارد یا جابه‌جا شده است.",
    genericTitle: "مشکلی پیش آمد",
    genericBody: "لطفاً دوباره تلاش کنید.",
    retry: "تلاش دوباره",
    domain: {
      NOT_FOUND: "مورد نظر پیدا نشد",
      VALIDATION: "اطلاعات واردشده نامعتبر است",
      CATEGORY_NOT_EMPTY: "ابتدا محصولات این دسته را منتقل کنید",
      CATEGORY_HAS_PRODUCTS: "ابتدا محصولات این دسته را منتقل کنید",
      DEPTH_EXCEEDED: "عمق دسته‌بندی نمی‌تواند بیش از دو سطح باشد",
      DUPLICATE_NAME: "این نام از قبل استفاده شده است",
      INVALID_DISCOUNT: "قیمت با تخفیف باید کمتر از قیمت اصلی باشد",
      DISCOUNT_WITH_VARIANTS: "برای محصول دارای تنوع نمی‌توان تخفیف گذاشت",
      NOT_LEAF_CATEGORY: "محصول فقط در دستهٔ بدون زیرشاخه ثبت می‌شود",
      INVALID_REORDER: "ترتیب ارسال‌شده نامعتبر است",
      INVALID_UPLOAD: "فایل تصویر نامعتبر است",
      INVALID_CREDENTIALS: "نام کاربری یا رمز عبور نادرست است",
      UNAUTHORIZED: "نشست شما معتبر نیست",
      RATE_LIMITED: "تعداد تلاش‌ها بیش از حد مجاز است؛ ۱۵ دقیقه دیگر تلاش کنید",
    },
  },
  auth: {
    title: "ورود به پنل",
    username: "نام کاربری",
    password: "رمز عبور",
    submit: "ورود",
    logout: "خروج",
    changePassword: "تغییر رمز عبور",
    currentPassword: "رمز فعلی",
    nextPassword: "رمز جدید",
    savePassword: "ذخیره رمز",
    passwordChanged: "رمز عبور به‌روزرسانی شد",
  },
  admin: {
    productsHeading: "محصولات",
    settingsHeading: "تنظیمات",
    restaurantName: "نام رستوران",
    unavailableMode: "وضعیت ناموجودها",
    unavailableMuted: "نمایش کم‌رنگ",
    unavailableHide: "پنهان کردن",
    save: "ذخیره",
    settingsSaved: "تنظیمات ذخیره شد",
  },
} as const;

export type StringKey = typeof strings;